server:
  port: 8081

dubbo:
  application:
    name: dubbo-demo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.dm.dubbo.service
  protocols:
    p1:
      id: dubbo1
      name: dubbo
      port: 20881
      host: 0.0.0.0
    p2:
      id: dubbo2
      name: dubbo
      port: 20882
      host: 0.0.0.0
