server:
  port: 8081

dubbo:
  application:
    name: dubbo-demo-provider
  registry:
    address: zookeeper://localhost:2181?timeout=20000
  scan:
    base-packages: com.dm.dubbo.service
  config-center:
    config-file: demo-provider
    address: zookeeper://localhost:2181?timeout=20000
    app-config-file: app-demo-provider
    highest-priority: false
  protocols:
    p1:
      id: dubbo1
      name: dubbo
      port: 20881
      host: 0.0.0.0
    p2:
      id: dubbo2
      name: dubbo
      port: 20882
      host: 0.0.0.0

